# Generated by Django 3.1.3 on 2020-11-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0002_imageuploadmodel_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='text',
        ),
    ]
