# Generated by Django 3.1.3 on 2020-11-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0003_remove_imageuploadmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadmodel',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
