# Generated by Django 3.1.3 on 2020-11-17 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0004_imageuploadmodel_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='text',
        ),
    ]
