# Generated by Django 3.1.3 on 2020-11-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0006_imageuploadmodel_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='PillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ITEM_IMAGE', models.ImageField(upload_to='')),
                ('ITEM_NAME', models.CharField(blank=True, max_length=255)),
                ('CLASS_NAME', models.CharField(blank=True, max_length=255)),
                ('ENTP_NAME', models.CharField(blank=True, max_length=255)),
                ('ETC_OTC_NAME', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='Result',
        ),
    ]
