# Generated by Django 3.1.3 on 2020-11-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0008_auto_20201118_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilllist',
            options={'managed': False},
        ),
    ]
