# Generated by Django 3.1.3 on 2020-11-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0009_auto_20201118_1916'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pilllist',
            table='pilllist',
        ),
    ]
